class SuraModel {
  final int suraNumber;
  final String SuraNameEn;
  final String SuraNameAr;
  final int versesCount;

  SuraModel({
    required this.suraNumber,
    required this.SuraNameEn,
    required this.SuraNameAr,
    required this.versesCount,
  });

  static List<SuraModel> suras_list = [
    SuraModel(
      suraNumber: 1,
      SuraNameEn: "Al-Fatiha",
      SuraNameAr: "الفاتحة",
      versesCount: 7,
    ),
    SuraModel(
      suraNumber: 2,
      SuraNameEn: "Al-Baqarah",
      SuraNameAr: "البقرة",
      versesCount: 286,
    ),
    SuraModel(
      suraNumber: 3,
      SuraNameEn: "Aal-E-Imran",
      SuraNameAr: "آل عمران",
      versesCount: 200,
    ),
    SuraModel(
      suraNumber: 4,
      SuraNameEn: "An-Nisa",
      SuraNameAr: "النساء",
      versesCount: 176,
    ),
    SuraModel(
      suraNumber: 5,
      SuraNameEn: "Al-Ma'idah",
      SuraNameAr: "المائدة",
      versesCount: 120,
    ),
    SuraModel(
      suraNumber: 6,
      SuraNameEn: "Al-An'am",
      SuraNameAr: "الأنعام",
      versesCount: 165,
    ),
    SuraModel(
      suraNumber: 7,
      SuraNameEn: "Al-A'raf",
      SuraNameAr: "الأعراف",
      versesCount: 206,
    ),
    SuraModel(
      suraNumber: 8,
      SuraNameEn: "Al-Anfal",
      SuraNameAr: "الأنفال",
      versesCount: 75,
    ),
    SuraModel(
      suraNumber: 9,
      SuraNameEn: "At-Tawbah",
      SuraNameAr: "التوبة",
      versesCount: 129,
    ),
    SuraModel(
      suraNumber: 10,
      SuraNameEn: "Yunus",
      SuraNameAr: "يونس",
      versesCount: 109,
    ),
    SuraModel(
      suraNumber: 11,
      SuraNameEn: "Hud",
      SuraNameAr: "هود",
      versesCount: 123,
    ),
    SuraModel(
      suraNumber: 12,
      SuraNameEn: "Yusuf",
      SuraNameAr: "يوسف",
      versesCount: 111,
    ),
    SuraModel(
      suraNumber: 13,
      SuraNameEn: "Ar-Ra'd",
      SuraNameAr: "الرعد",
      versesCount: 43,
    ),
    SuraModel(
      suraNumber: 14,
      SuraNameEn: "Ibrahim",
      SuraNameAr: "إبراهيم",
      versesCount: 52,
    ),
    SuraModel(
      suraNumber: 15,
      SuraNameEn: "Al-Hijr",
      SuraNameAr: "الحجر",
      versesCount: 99,
    ),
    SuraModel(
      suraNumber: 16,
      SuraNameEn: "An-Nahl",
      SuraNameAr: "النحل",
      versesCount: 128,
    ),
    SuraModel(
      suraNumber: 17,
      SuraNameEn: "Al-Isra",
      SuraNameAr: "الإسراء",
      versesCount: 111,
    ),
    SuraModel(
      suraNumber: 18,
      SuraNameEn: "Al-Kahf",
      SuraNameAr: "الكهف",
      versesCount: 110,
    ),
    SuraModel(
      suraNumber: 19,
      SuraNameEn: "Maryam",
      SuraNameAr: "مريم",
      versesCount: 98,
    ),
    SuraModel(
      suraNumber: 20,
      SuraNameEn: "Ta-Ha",
      SuraNameAr: "طه",
      versesCount: 135,
    ),
    SuraModel(
      suraNumber: 21,
      SuraNameEn: "Al-Anbiya",
      SuraNameAr: "الأنبياء",
      versesCount: 112,
    ),
    SuraModel(
      suraNumber: 22,
      SuraNameEn: "Al-Hajj",
      SuraNameAr: "الحج",
      versesCount: 78,
    ),
    SuraModel(
      suraNumber: 23,
      SuraNameEn: "Al-Mu’minun",
      SuraNameAr: "المؤمنون",
      versesCount: 118,
    ),
    SuraModel(
      suraNumber: 24,
      SuraNameEn: "An-Nur",
      SuraNameAr: "النور",
      versesCount: 64,
    ),
    SuraModel(
      suraNumber: 25,
      SuraNameEn: "Al-Furqan",
      SuraNameAr: "الفرقان",
      versesCount: 77,
    ),
    SuraModel(
      suraNumber: 26,
      SuraNameEn: "Ash-Shu'ara",
      SuraNameAr: "الشعراء",
      versesCount: 227,
    ),
    SuraModel(
      suraNumber: 27,
      SuraNameEn: "An-Naml",
      SuraNameAr: "النمل",
      versesCount: 93,
    ),
    SuraModel(
      suraNumber: 28,
      SuraNameEn: "Al-Qasas",
      SuraNameAr: "القصص",
      versesCount: 88,
    ),
    SuraModel(
      suraNumber: 29,
      SuraNameEn: "Al-Ankabut",
      SuraNameAr: "العنكبوت",
      versesCount: 69,
    ),
    SuraModel(
      suraNumber: 30,
      SuraNameEn: "Ar-Rum",
      SuraNameAr: "الروم",
      versesCount: 60,
    ),
    SuraModel(
      suraNumber: 31,
      SuraNameEn: "Luqman",
      SuraNameAr: "لقمان",
      versesCount: 34,
    ),
    SuraModel(
      suraNumber: 32,
      SuraNameEn: "As-Sajdah",
      SuraNameAr: "السجدة",
      versesCount: 30,
    ),
    SuraModel(
      suraNumber: 33,
      SuraNameEn: "Al-Ahzab",
      SuraNameAr: "الأحزاب",
      versesCount: 73,
    ),
    SuraModel(
      suraNumber: 34,
      SuraNameEn: "Saba",
      SuraNameAr: "سبأ",
      versesCount: 54,
    ),
    SuraModel(
      suraNumber: 35,
      SuraNameEn: "Fatir",
      SuraNameAr: "فاطر",
      versesCount: 45,
    ),
    SuraModel(
      suraNumber: 36,
      SuraNameEn: "Ya-Sin",
      SuraNameAr: "يس",
      versesCount: 83,
    ),
    SuraModel(
      suraNumber: 37,
      SuraNameEn: "As-Saffat",
      SuraNameAr: "الصافات",
      versesCount: 182,
    ),
    SuraModel(suraNumber: 38, SuraNameEn: "Sad", SuraNameAr: "ص", versesCount: 88),
    SuraModel(
      suraNumber: 39,
      SuraNameEn: "Az-Zumar",
      SuraNameAr: "الزمر",
      versesCount: 75,
    ),
    SuraModel(
      suraNumber: 40,
      SuraNameEn: "Ghafir",
      SuraNameAr: "غافر",
      versesCount: 85,
    ),
    SuraModel(
      suraNumber: 41,
      SuraNameEn: "Fussilat",
      SuraNameAr: "فصلت",
      versesCount: 54,
    ),
    SuraModel(
      suraNumber: 42,
      SuraNameEn: "Ash-Shura",
      SuraNameAr: "الشورى",
      versesCount: 53,
    ),
    SuraModel(
      suraNumber: 43,
      SuraNameEn: "Az-Zukhruf",
      SuraNameAr: "الزخرف",
      versesCount: 89,
    ),
    SuraModel(
      suraNumber: 44,
      SuraNameEn: "Ad-Dukhan",
      SuraNameAr: "الدخان",
      versesCount: 59,
    ),
    SuraModel(
      suraNumber: 45,
      SuraNameEn: "Al-Jathiyah",
      SuraNameAr: "الجاثية",
      versesCount: 37,
    ),
    SuraModel(
      suraNumber: 46,
      SuraNameEn: "Al-Ahqaf",
      SuraNameAr: "الأحقاف",
      versesCount: 35,
    ),
    SuraModel(
      suraNumber: 47,
      SuraNameEn: "Muhammad",
      SuraNameAr: "محمد",
      versesCount: 38,
    ),
    SuraModel(
      suraNumber: 48,
      SuraNameEn: "Al-Fath",
      SuraNameAr: "الفتح",
      versesCount: 29,
    ),
    SuraModel(
      suraNumber: 49,
      SuraNameEn: "Al-Hujurat",
      SuraNameAr: "الحجرات",
      versesCount: 18,
    ),
    SuraModel(suraNumber: 50, SuraNameEn: "Qaf", SuraNameAr: "ق", versesCount: 45),
    SuraModel(
      suraNumber: 51,
      SuraNameEn: "Adh-Dhariyat",
      SuraNameAr: "الذاريات",
      versesCount: 60,
    ),
    SuraModel(
      suraNumber: 52,
      SuraNameEn: "At-Tur",
      SuraNameAr: "الطور",
      versesCount: 49,
    ),
    SuraModel(
      suraNumber: 53,
      SuraNameEn: "An-Najm",
      SuraNameAr: "النجم",
      versesCount: 62,
    ),
    SuraModel(
      suraNumber: 54,
      SuraNameEn: "Al-Qamar",
      SuraNameAr: "القمر",
      versesCount: 55,
    ),
    SuraModel(
      suraNumber: 55,
      SuraNameEn: "Ar-Rahman",
      SuraNameAr: "الرحمن",
      versesCount: 78,
    ),
    SuraModel(
      suraNumber: 56,
      SuraNameEn: "Al-Waqia",
      SuraNameAr: "الواقعة",
      versesCount: 96,
    ),
    SuraModel(
      suraNumber: 57,
      SuraNameEn: "Al-Hadid",
      SuraNameAr: "الحديد",
      versesCount: 29,
    ),
    SuraModel(
      suraNumber: 58,
      SuraNameEn: "Al-Mujadila",
      SuraNameAr: "المجادلة",
      versesCount: 22,
    ),
    SuraModel(
      suraNumber: 59,
      SuraNameEn: "Al-Hashr",
      SuraNameAr: "الحشر",
      versesCount: 24,
    ),
    SuraModel(
      suraNumber: 60,
      SuraNameEn: "Al-Mumtahina",
      SuraNameAr: "الممتحنة",
      versesCount: 13,
    ),
    SuraModel(
      suraNumber: 61,
      SuraNameEn: "As-Saff",
      SuraNameAr: "الصف",
      versesCount: 14,
    ),
    SuraModel(
      suraNumber: 62,
      SuraNameEn: "Al-Jumuah",
      SuraNameAr: "الجمعة",
      versesCount: 11,
    ),
    SuraModel(
      suraNumber: 63,
      SuraNameEn: "Al-Munafiqun",
      SuraNameAr: "المنافقون",
      versesCount: 11,
    ),
    SuraModel(
      suraNumber: 64,
      SuraNameEn: "At-Taghabun",
      SuraNameAr: "التغابن",
      versesCount: 18,
    ),
    SuraModel(
      suraNumber: 65,
      SuraNameEn: "At-Talaq",
      SuraNameAr: "الطلاق",
      versesCount: 12,
    ),
    SuraModel(
      suraNumber: 66,
      SuraNameEn: "At-Tahrim",
      SuraNameAr: "التحريم",
      versesCount: 12,
    ),
    SuraModel(
      suraNumber: 67,
      SuraNameEn: "Al-Mulk",
      SuraNameAr: "الملك",
      versesCount: 30,
    ),
    SuraModel(
      suraNumber: 68,
      SuraNameEn: "Al-Qalam",
      SuraNameAr: "القلم",
      versesCount: 52,
    ),
    SuraModel(
      suraNumber: 69,
      SuraNameEn: "Al-Haqqah",
      SuraNameAr: "الحاقة",
      versesCount: 52,
    ),
    SuraModel(
      suraNumber: 70,
      SuraNameEn: "Al-Ma'arij",
      SuraNameAr: "المعارج",
      versesCount: 44,
    ),
    SuraModel(
      suraNumber: 71,
      SuraNameEn: "Nuh",
      SuraNameAr: "نوح",
      versesCount: 28,
    ),
    SuraModel(
      suraNumber: 72,
      SuraNameEn: "Al-Jinn",
      SuraNameAr: "الجن",
      versesCount: 28,
    ),
    SuraModel(
      suraNumber: 73,
      SuraNameEn: "Al-Muzzammil",
      SuraNameAr: "المزمل",
      versesCount: 20,
    ),
    SuraModel(
      suraNumber: 74,
      SuraNameEn: "Al-Muddaththir",
      SuraNameAr: "المدثر",
      versesCount: 56,
    ),
    SuraModel(
      suraNumber: 75,
      SuraNameEn: "Al-Qiyamah",
      SuraNameAr: "القيامة",
      versesCount: 40,
    ),
    SuraModel(
      suraNumber: 76,
      SuraNameEn: "Al-Insan",
      SuraNameAr: "الانسان",
      versesCount: 31,
    ),
    SuraModel(
      suraNumber: 77,
      SuraNameEn: "Al-Mursalat",
      SuraNameAr: "المرسلات",
      versesCount: 50,
    ),
    SuraModel(
      suraNumber: 78,
      SuraNameEn: "An-Naba",
      SuraNameAr: "النبأ",
      versesCount: 40,
    ),
    SuraModel(
      suraNumber: 79,
      SuraNameEn: "An-Nazi'at",
      SuraNameAr: "النازعات",
      versesCount: 46,
    ),
    SuraModel(
      suraNumber: 80,
      SuraNameEn: "Abasa",
      SuraNameAr: "عبس",
      versesCount: 42,
    ),
    SuraModel(
      suraNumber: 81,
      SuraNameEn: "At-Takwir",
      SuraNameAr: "التكوير",
      versesCount: 29,
    ),
    SuraModel(
      suraNumber: 82,
      SuraNameEn: "Al-Infitar",
      SuraNameAr: "الإنفطار",
      versesCount: 19,
    ),
    SuraModel(
      suraNumber: 83,
      SuraNameEn: "Al-Mutaffifin",
      SuraNameAr: "المطففين",
      versesCount: 36,
    ),
    SuraModel(
      suraNumber: 84,
      SuraNameEn: "Al-Inshiqaq",
      SuraNameAr: "الإنشقاق",
      versesCount: 25,
    ),
    SuraModel(
      suraNumber: 85,
      SuraNameEn: "Al-Buruj",
      SuraNameAr: "البروج",
      versesCount: 22,
    ),
    SuraModel(
      suraNumber: 86,
      SuraNameEn: "At-Tariq",
      SuraNameAr: "الطارق",
      versesCount: 17,
    ),
    SuraModel(
      suraNumber: 87,
      SuraNameEn: "Al-Ala",
      SuraNameAr: "الأعلى",
      versesCount: 19,
    ),
    SuraModel(
      suraNumber: 88,
      SuraNameEn: "Al-Ghashiyah",
      SuraNameAr: "الغاشية",
      versesCount: 26,
    ),
    SuraModel(
      suraNumber: 89,
      SuraNameEn: "Al-Fajr",
      SuraNameAr: "الفجر",
      versesCount: 30,
    ),
    SuraModel(
      suraNumber: 90,
      SuraNameEn: "Al-Balad",
      SuraNameAr: "البلد",
      versesCount: 20,
    ),
    SuraModel(
      suraNumber: 91,
      SuraNameEn: "Ash-Shams",
      SuraNameAr: "الشمس",
      versesCount: 15,
    ),
    SuraModel(
      suraNumber: 92,
      SuraNameEn: "Al-Lail",
      SuraNameAr: "الليل",
      versesCount: 21,
    ),
    SuraModel(
      suraNumber: 93,
      SuraNameEn: "Ad-Duha",
      SuraNameAr: "الضحى",
      versesCount: 11,
    ),
    SuraModel(
      suraNumber: 94,
      SuraNameEn: "Ash-Sharh",
      SuraNameAr: "الشرح",
      versesCount: 8,
    ),
    SuraModel(
      suraNumber: 95,
      SuraNameEn: "At-Tin",
      SuraNameAr: "التين",
      versesCount: 8,
    ),
    SuraModel(
      suraNumber: 96,
      SuraNameEn: "Al-Alaq",
      SuraNameAr: "العلق",
      versesCount: 19,
    ),
    SuraModel(
      suraNumber: 97,
      SuraNameEn: "Al-Qadr",
      SuraNameAr: "القدر",
      versesCount: 5,
    ),
    SuraModel(
      suraNumber: 98,
      SuraNameEn: "Al-Bayyinah",
      SuraNameAr: "البينة",
      versesCount: 8,
    ),
    SuraModel(
      suraNumber: 99,
      SuraNameEn: "Az-Zalzalah",
      SuraNameAr: "الزلزلة",
      versesCount: 8,
    ),
    SuraModel(
      suraNumber: 100,
      SuraNameEn: "Al-Adiyat",
      SuraNameAr: "العاديات",
      versesCount: 11,
    ),
    SuraModel(
      suraNumber: 101,
      SuraNameEn: "Al-Qari'ah",
      SuraNameAr: "القارعة",
      versesCount: 11,
    ),
    SuraModel(
      suraNumber: 102,
      SuraNameEn: "At-Takathur",
      SuraNameAr: "التكاثر",
      versesCount: 8,
    ),
    SuraModel(
      suraNumber: 103,
      SuraNameEn: "Al-Asr",
      SuraNameAr: "العصر",
      versesCount: 3,
    ),
    SuraModel(
      suraNumber: 104,
      SuraNameEn: "Al-Humazah",
      SuraNameAr: "الهمزة",
      versesCount: 9,
    ),
    SuraModel(
      suraNumber: 105,
      SuraNameEn: "Al-Fil",
      SuraNameAr: "الفيل",
      versesCount: 5,
    ),
    SuraModel(
      suraNumber: 106,
      SuraNameEn: "Quraish",
      SuraNameAr: "قريش",
      versesCount: 4,
    ),
    SuraModel(
      suraNumber: 107,
      SuraNameEn: "Al-Ma'un",
      SuraNameAr: "الماعون",
      versesCount: 7,
    ),
    SuraModel(
      suraNumber: 108,
      SuraNameEn: "Al-Kawthar",
      SuraNameAr: "الكوثر",
      versesCount: 3,
    ),
    SuraModel(
      suraNumber: 109,
      SuraNameEn: "Al-Kafirun",
      SuraNameAr: "الكافرون",
      versesCount: 6,
    ),
    SuraModel(
      suraNumber: 110,
      SuraNameEn: "An-Nasr",
      SuraNameAr: "النصر",
      versesCount: 3,
    ),
    SuraModel(
      suraNumber: 111,
      SuraNameEn: "Al-Masad",
      SuraNameAr: "المسد",
      versesCount: 5,
    ),
    SuraModel(
      suraNumber: 112,
      SuraNameEn: "Al-Ikhlas",
      SuraNameAr: "الإخلاص",
      versesCount: 4,
    ),
    SuraModel(
      suraNumber: 113,
      SuraNameEn: "Al-Falaq",
      SuraNameAr: "الفلق",
      versesCount: 5,
    ),
    SuraModel(
      suraNumber: 114,
      SuraNameEn: "An-Nas",
      SuraNameAr: "الناس",
      versesCount: 6,
    ),
  ];
}
