class SuraModel {
  final int number;
  final String SuraNameEn;
  final String SuraNameAr;
  final int versesCount;

  SuraModel({
    required this.number,
    required this.SuraNameEn,
    required this.SuraNameAr,
    required this.versesCount,
  });

  static List<SuraModel> suras_list = [
    SuraModel(
      number: 1,
      SuraNameEn: "Al-Fatiha",
      SuraNameAr: "الفاتحة",
      versesCount: 7,
    ),
    SuraModel(
      number: 2,
      SuraNameEn: "Al-Baqarah",
      SuraNameAr: "البقرة",
      versesCount: 286,
    ),
    SuraModel(
      number: 3,
      SuraNameEn: "Aal-E-Imran",
      SuraNameAr: "آل عمران",
      versesCount: 200,
    ),
    SuraModel(
      number: 4,
      SuraNameEn: "An-Nisa",
      SuraNameAr: "النساء",
      versesCount: 176,
    ),
    SuraModel(
      number: 5,
      SuraNameEn: "Al-Ma'idah",
      SuraNameAr: "المائدة",
      versesCount: 120,
    ),
    SuraModel(
      number: 6,
      SuraNameEn: "Al-An'am",
      SuraNameAr: "الأنعام",
      versesCount: 165,
    ),
    SuraModel(
      number: 7,
      SuraNameEn: "Al-A'raf",
      SuraNameAr: "الأعراف",
      versesCount: 206,
    ),
    SuraModel(
      number: 8,
      SuraNameEn: "Al-Anfal",
      SuraNameAr: "الأنفال",
      versesCount: 75,
    ),
    SuraModel(
      number: 9,
      SuraNameEn: "At-Tawbah",
      SuraNameAr: "التوبة",
      versesCount: 129,
    ),
    SuraModel(
      number: 10,
      SuraNameEn: "Yunus",
      SuraNameAr: "يونس",
      versesCount: 109,
    ),
    SuraModel(
      number: 11,
      SuraNameEn: "Hud",
      SuraNameAr: "هود",
      versesCount: 123,
    ),
    SuraModel(
      number: 12,
      SuraNameEn: "Yusuf",
      SuraNameAr: "يوسف",
      versesCount: 111,
    ),
    SuraModel(
      number: 13,
      SuraNameEn: "Ar-Ra'd",
      SuraNameAr: "الرعد",
      versesCount: 43,
    ),
    SuraModel(
      number: 14,
      SuraNameEn: "Ibrahim",
      SuraNameAr: "إبراهيم",
      versesCount: 52,
    ),
    SuraModel(
      number: 15,
      SuraNameEn: "Al-Hijr",
      SuraNameAr: "الحجر",
      versesCount: 99,
    ),
    SuraModel(
      number: 16,
      SuraNameEn: "An-Nahl",
      SuraNameAr: "النحل",
      versesCount: 128,
    ),
    SuraModel(
      number: 17,
      SuraNameEn: "Al-Isra",
      SuraNameAr: "الإسراء",
      versesCount: 111,
    ),
    SuraModel(
      number: 18,
      SuraNameEn: "Al-Kahf",
      SuraNameAr: "الكهف",
      versesCount: 110,
    ),
    SuraModel(
      number: 19,
      SuraNameEn: "Maryam",
      SuraNameAr: "مريم",
      versesCount: 98,
    ),
    SuraModel(
      number: 20,
      SuraNameEn: "Ta-Ha",
      SuraNameAr: "طه",
      versesCount: 135,
    ),
    SuraModel(
      number: 21,
      SuraNameEn: "Al-Anbiya",
      SuraNameAr: "الأنبياء",
      versesCount: 112,
    ),
    SuraModel(
      number: 22,
      SuraNameEn: "Al-Hajj",
      SuraNameAr: "الحج",
      versesCount: 78,
    ),
    SuraModel(
      number: 23,
      SuraNameEn: "Al-Mu’minun",
      SuraNameAr: "المؤمنون",
      versesCount: 118,
    ),
    SuraModel(
      number: 24,
      SuraNameEn: "An-Nur",
      SuraNameAr: "النور",
      versesCount: 64,
    ),
    SuraModel(
      number: 25,
      SuraNameEn: "Al-Furqan",
      SuraNameAr: "الفرقان",
      versesCount: 77,
    ),
    SuraModel(
      number: 26,
      SuraNameEn: "Ash-Shu'ara",
      SuraNameAr: "الشعراء",
      versesCount: 227,
    ),
    SuraModel(
      number: 27,
      SuraNameEn: "An-Naml",
      SuraNameAr: "النمل",
      versesCount: 93,
    ),
    SuraModel(
      number: 28,
      SuraNameEn: "Al-Qasas",
      SuraNameAr: "القصص",
      versesCount: 88,
    ),
    SuraModel(
      number: 29,
      SuraNameEn: "Al-Ankabut",
      SuraNameAr: "العنكبوت",
      versesCount: 69,
    ),
    SuraModel(
      number: 30,
      SuraNameEn: "Ar-Rum",
      SuraNameAr: "الروم",
      versesCount: 60,
    ),
    SuraModel(
      number: 31,
      SuraNameEn: "Luqman",
      SuraNameAr: "لقمان",
      versesCount: 34,
    ),
    SuraModel(
      number: 32,
      SuraNameEn: "As-Sajdah",
      SuraNameAr: "السجدة",
      versesCount: 30,
    ),
    SuraModel(
      number: 33,
      SuraNameEn: "Al-Ahzab",
      SuraNameAr: "الأحزاب",
      versesCount: 73,
    ),
    SuraModel(
      number: 34,
      SuraNameEn: "Saba",
      SuraNameAr: "سبأ",
      versesCount: 54,
    ),
    SuraModel(
      number: 35,
      SuraNameEn: "Fatir",
      SuraNameAr: "فاطر",
      versesCount: 45,
    ),
    SuraModel(
      number: 36,
      SuraNameEn: "Ya-Sin",
      SuraNameAr: "يس",
      versesCount: 83,
    ),
    SuraModel(
      number: 37,
      SuraNameEn: "As-Saffat",
      SuraNameAr: "الصافات",
      versesCount: 182,
    ),
    SuraModel(number: 38, SuraNameEn: "Sad", SuraNameAr: "ص", versesCount: 88),
    SuraModel(
      number: 39,
      SuraNameEn: "Az-Zumar",
      SuraNameAr: "الزمر",
      versesCount: 75,
    ),
    SuraModel(
      number: 40,
      SuraNameEn: "Ghafir",
      SuraNameAr: "غافر",
      versesCount: 85,
    ),
    SuraModel(
      number: 41,
      SuraNameEn: "Fussilat",
      SuraNameAr: "فصلت",
      versesCount: 54,
    ),
    SuraModel(
      number: 42,
      SuraNameEn: "Ash-Shura",
      SuraNameAr: "الشورى",
      versesCount: 53,
    ),
    SuraModel(
      number: 43,
      SuraNameEn: "Az-Zukhruf",
      SuraNameAr: "الزخرف",
      versesCount: 89,
    ),
    SuraModel(
      number: 44,
      SuraNameEn: "Ad-Dukhan",
      SuraNameAr: "الدخان",
      versesCount: 59,
    ),
    SuraModel(
      number: 45,
      SuraNameEn: "Al-Jathiyah",
      SuraNameAr: "الجاثية",
      versesCount: 37,
    ),
    SuraModel(
      number: 46,
      SuraNameEn: "Al-Ahqaf",
      SuraNameAr: "الأحقاف",
      versesCount: 35,
    ),
    SuraModel(
      number: 47,
      SuraNameEn: "Muhammad",
      SuraNameAr: "محمد",
      versesCount: 38,
    ),
    SuraModel(
      number: 48,
      SuraNameEn: "Al-Fath",
      SuraNameAr: "الفتح",
      versesCount: 29,
    ),
    SuraModel(
      number: 49,
      SuraNameEn: "Al-Hujurat",
      SuraNameAr: "الحجرات",
      versesCount: 18,
    ),
    SuraModel(number: 50, SuraNameEn: "Qaf", SuraNameAr: "ق", versesCount: 45),
    SuraModel(
      number: 51,
      SuraNameEn: "Adh-Dhariyat",
      SuraNameAr: "الذاريات",
      versesCount: 60,
    ),
    SuraModel(
      number: 52,
      SuraNameEn: "At-Tur",
      SuraNameAr: "الطور",
      versesCount: 49,
    ),
    SuraModel(
      number: 53,
      SuraNameEn: "An-Najm",
      SuraNameAr: "النجم",
      versesCount: 62,
    ),
    SuraModel(
      number: 54,
      SuraNameEn: "Al-Qamar",
      SuraNameAr: "القمر",
      versesCount: 55,
    ),
    SuraModel(
      number: 55,
      SuraNameEn: "Ar-Rahman",
      SuraNameAr: "الرحمن",
      versesCount: 78,
    ),
    SuraModel(
      number: 56,
      SuraNameEn: "Al-Waqia",
      SuraNameAr: "الواقعة",
      versesCount: 96,
    ),
    SuraModel(
      number: 57,
      SuraNameEn: "Al-Hadid",
      SuraNameAr: "الحديد",
      versesCount: 29,
    ),
    SuraModel(
      number: 58,
      SuraNameEn: "Al-Mujadila",
      SuraNameAr: "المجادلة",
      versesCount: 22,
    ),
    SuraModel(
      number: 59,
      SuraNameEn: "Al-Hashr",
      SuraNameAr: "الحشر",
      versesCount: 24,
    ),
    SuraModel(
      number: 60,
      SuraNameEn: "Al-Mumtahina",
      SuraNameAr: "الممتحنة",
      versesCount: 13,
    ),
    SuraModel(
      number: 61,
      SuraNameEn: "As-Saff",
      SuraNameAr: "الصف",
      versesCount: 14,
    ),
    SuraModel(
      number: 62,
      SuraNameEn: "Al-Jumuah",
      SuraNameAr: "الجمعة",
      versesCount: 11,
    ),
    SuraModel(
      number: 63,
      SuraNameEn: "Al-Munafiqun",
      SuraNameAr: "المنافقون",
      versesCount: 11,
    ),
    SuraModel(
      number: 64,
      SuraNameEn: "At-Taghabun",
      SuraNameAr: "التغابن",
      versesCount: 18,
    ),
    SuraModel(
      number: 65,
      SuraNameEn: "At-Talaq",
      SuraNameAr: "الطلاق",
      versesCount: 12,
    ),
    SuraModel(
      number: 66,
      SuraNameEn: "At-Tahrim",
      SuraNameAr: "التحريم",
      versesCount: 12,
    ),
    SuraModel(
      number: 67,
      SuraNameEn: "Al-Mulk",
      SuraNameAr: "الملك",
      versesCount: 30,
    ),
    SuraModel(
      number: 68,
      SuraNameEn: "Al-Qalam",
      SuraNameAr: "القلم",
      versesCount: 52,
    ),
    SuraModel(
      number: 69,
      SuraNameEn: "Al-Haqqah",
      SuraNameAr: "الحاقة",
      versesCount: 52,
    ),
    SuraModel(
      number: 70,
      SuraNameEn: "Al-Ma'arij",
      SuraNameAr: "المعارج",
      versesCount: 44,
    ),
    SuraModel(
      number: 71,
      SuraNameEn: "Nuh",
      SuraNameAr: "نوح",
      versesCount: 28,
    ),
    SuraModel(
      number: 72,
      SuraNameEn: "Al-Jinn",
      SuraNameAr: "الجن",
      versesCount: 28,
    ),
    SuraModel(
      number: 73,
      SuraNameEn: "Al-Muzzammil",
      SuraNameAr: "المزمل",
      versesCount: 20,
    ),
    SuraModel(
      number: 74,
      SuraNameEn: "Al-Muddaththir",
      SuraNameAr: "المدثر",
      versesCount: 56,
    ),
    SuraModel(
      number: 75,
      SuraNameEn: "Al-Qiyamah",
      SuraNameAr: "القيامة",
      versesCount: 40,
    ),
    SuraModel(
      number: 76,
      SuraNameEn: "Al-Insan",
      SuraNameAr: "الانسان",
      versesCount: 31,
    ),
    SuraModel(
      number: 77,
      SuraNameEn: "Al-Mursalat",
      SuraNameAr: "المرسلات",
      versesCount: 50,
    ),
    SuraModel(
      number: 78,
      SuraNameEn: "An-Naba",
      SuraNameAr: "النبأ",
      versesCount: 40,
    ),
    SuraModel(
      number: 79,
      SuraNameEn: "An-Nazi'at",
      SuraNameAr: "النازعات",
      versesCount: 46,
    ),
    SuraModel(
      number: 80,
      SuraNameEn: "Abasa",
      SuraNameAr: "عبس",
      versesCount: 42,
    ),
    SuraModel(
      number: 81,
      SuraNameEn: "At-Takwir",
      SuraNameAr: "التكوير",
      versesCount: 29,
    ),
    SuraModel(
      number: 82,
      SuraNameEn: "Al-Infitar",
      SuraNameAr: "الإنفطار",
      versesCount: 19,
    ),
    SuraModel(
      number: 83,
      SuraNameEn: "Al-Mutaffifin",
      SuraNameAr: "المطففين",
      versesCount: 36,
    ),
    SuraModel(
      number: 84,
      SuraNameEn: "Al-Inshiqaq",
      SuraNameAr: "الإنشقاق",
      versesCount: 25,
    ),
    SuraModel(
      number: 85,
      SuraNameEn: "Al-Buruj",
      SuraNameAr: "البروج",
      versesCount: 22,
    ),
    SuraModel(
      number: 86,
      SuraNameEn: "At-Tariq",
      SuraNameAr: "الطارق",
      versesCount: 17,
    ),
    SuraModel(
      number: 87,
      SuraNameEn: "Al-Ala",
      SuraNameAr: "الأعلى",
      versesCount: 19,
    ),
    SuraModel(
      number: 88,
      SuraNameEn: "Al-Ghashiyah",
      SuraNameAr: "الغاشية",
      versesCount: 26,
    ),
    SuraModel(
      number: 89,
      SuraNameEn: "Al-Fajr",
      SuraNameAr: "الفجر",
      versesCount: 30,
    ),
    SuraModel(
      number: 90,
      SuraNameEn: "Al-Balad",
      SuraNameAr: "البلد",
      versesCount: 20,
    ),
    SuraModel(
      number: 91,
      SuraNameEn: "Ash-Shams",
      SuraNameAr: "الشمس",
      versesCount: 15,
    ),
    SuraModel(
      number: 92,
      SuraNameEn: "Al-Lail",
      SuraNameAr: "الليل",
      versesCount: 21,
    ),
    SuraModel(
      number: 93,
      SuraNameEn: "Ad-Duha",
      SuraNameAr: "الضحى",
      versesCount: 11,
    ),
    SuraModel(
      number: 94,
      SuraNameEn: "Ash-Sharh",
      SuraNameAr: "الشرح",
      versesCount: 8,
    ),
    SuraModel(
      number: 95,
      SuraNameEn: "At-Tin",
      SuraNameAr: "التين",
      versesCount: 8,
    ),
    SuraModel(
      number: 96,
      SuraNameEn: "Al-Alaq",
      SuraNameAr: "العلق",
      versesCount: 19,
    ),
    SuraModel(
      number: 97,
      SuraNameEn: "Al-Qadr",
      SuraNameAr: "القدر",
      versesCount: 5,
    ),
    SuraModel(
      number: 98,
      SuraNameEn: "Al-Bayyinah",
      SuraNameAr: "البينة",
      versesCount: 8,
    ),
    SuraModel(
      number: 99,
      SuraNameEn: "Az-Zalzalah",
      SuraNameAr: "الزلزلة",
      versesCount: 8,
    ),
    SuraModel(
      number: 100,
      SuraNameEn: "Al-Adiyat",
      SuraNameAr: "العاديات",
      versesCount: 11,
    ),
    SuraModel(
      number: 101,
      SuraNameEn: "Al-Qari'ah",
      SuraNameAr: "القارعة",
      versesCount: 11,
    ),
    SuraModel(
      number: 102,
      SuraNameEn: "At-Takathur",
      SuraNameAr: "التكاثر",
      versesCount: 8,
    ),
    SuraModel(
      number: 103,
      SuraNameEn: "Al-Asr",
      SuraNameAr: "العصر",
      versesCount: 3,
    ),
    SuraModel(
      number: 104,
      SuraNameEn: "Al-Humazah",
      SuraNameAr: "الهمزة",
      versesCount: 9,
    ),
    SuraModel(
      number: 105,
      SuraNameEn: "Al-Fil",
      SuraNameAr: "الفيل",
      versesCount: 5,
    ),
    SuraModel(
      number: 106,
      SuraNameEn: "Quraish",
      SuraNameAr: "قريش",
      versesCount: 4,
    ),
    SuraModel(
      number: 107,
      SuraNameEn: "Al-Ma'un",
      SuraNameAr: "الماعون",
      versesCount: 7,
    ),
    SuraModel(
      number: 108,
      SuraNameEn: "Al-Kawthar",
      SuraNameAr: "الكوثر",
      versesCount: 3,
    ),
    SuraModel(
      number: 109,
      SuraNameEn: "Al-Kafirun",
      SuraNameAr: "الكافرون",
      versesCount: 6,
    ),
    SuraModel(
      number: 110,
      SuraNameEn: "An-Nasr",
      SuraNameAr: "النصر",
      versesCount: 3,
    ),
    SuraModel(
      number: 111,
      SuraNameEn: "Al-Masad",
      SuraNameAr: "المسد",
      versesCount: 5,
    ),
    SuraModel(
      number: 112,
      SuraNameEn: "Al-Ikhlas",
      SuraNameAr: "الإخلاص",
      versesCount: 4,
    ),
    SuraModel(
      number: 113,
      SuraNameEn: "Al-Falaq",
      SuraNameAr: "الفلق",
      versesCount: 5,
    ),
    SuraModel(
      number: 114,
      SuraNameEn: "An-Nas",
      SuraNameAr: "الناس",
      versesCount: 6,
    ),
  ];
}
